In [1]:
pip install quandl

Requirement already satisfied: quandl in /opt/anaconda3/lib/python3.7/site-packages (3.6.1)
Requirement already satisfied: requests>=2.7.0 in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (2.22.0)
Requirement already satisfied: more-itertools in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (8.2.0)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (2.8.1)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (1.14.0)
Requirement already satisfied: inflection>=0.3.1 in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (0.5.1)
Requirement already satisfied: numpy>=1.8 in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (1.18.1)
Requirement already satisfied: pandas>=0.14 in /opt/anaconda3/lib/python3.7/site-packages (from quandl) (1.0.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from requests>=2.7.0->quandl) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests>=2.7.0->quandl) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests>=2.7.0->quandl) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.7/site-packages (from requests>=2.7.0->quandl) (2019.11.28)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.14->quandl) (2019.3)
Note: you may need to restart the kernel to use updated packages.

In [305]:
import quandl
import pandas as pd
import os
import random

#https://www.quandl.com/data/EUREX-EUREX-Futures-Data
#https://www.quandl.com/data/RATEINF/INFLATION_USA-Inflation-YOY-USA

In [4]:
quandl.ApiConfig.api_key = 'qoZr9QNEwYKyHJymGzEg'


#quandl.ApiConfig.api_key ="youtoken"

In [172]:
#1.Bitcoin_my_wallet_num_users
Bitcoin_my_wallet_num_users = quandl.get("BCHAIN/MWNUS")

Bitcoin_my_wallet_num_users['Date'] = Bitcoin_my_wallet_num_users.index
Bitcoin_my_wallet_num_users.shape

(4527, 2)

In [164]:
Name_Vec.append('Bitcoin_my_wallet_num_users')

In [165]:
#2.BitCoin USD Exchange Volume
Volume = quandl.get('BCHAIN/TRVOU')
Volume['Date']= Volume.index
Name_Vec.append('Volume')

Volume.shape

(4561, 2)

In [145]:
#3. Bitcoin Difficulty
Difficulty = quandl.get('BCHAIN/DIFF')
Difficulty['Date'] = Difficulty.index
Name_Vec.append('Difficulty')        
Difficulty.shape

(4560, 2)

In [155]:
#4. Bitcoin my wallet num of transaction per day
wallet_num_transaction = quandl.get('BCHAIN/MWNTD')
wallet_num_transaction['Date'] = wallet_num_transaction.index
Name_Vec.append('wallet_num_transaction')
wallet_num_transaction.shape

(4523, 2)

In [166]:
#5.Bitcoin My Wallet Transaction Volume
wallet_transaction_volume = quandl.get('BCHAIN/MWTRV')
wallet_transaction_volume['Date'] = wallet_transaction_volume.index
Name_Vec.append('wallet_transaction_volume')
wallet_transaction_volume.shape

(4523, 2)

In [169]:
#6. Bitcoin Avg Block Size
Bitcoin_Avg_Block_Size = quandl.get('BCHAIN/AVBLS')
Bitcoin_Avg_Block_Size['Date'] = Bitcoin_Avg_Block_Size.index
Name_Vec.append('Bitcoin_Avg_Block_Size')
Bitcoin_Avg_Block_Size.shape

(4560, 2)

In [175]:
#7. Bitcoin Miners Revenue
Miners_Revenue = quandl.get('BCHAIN/MIREV')
Miners_Revenue['Date'] = Miners_Revenue.index
Name_Vec.append('Miners_Revenue')
Miners_Revenue.shape

(4560, 2)

In [178]:
#8. Bitcoin Hash Rate
Hash_Rate = quandl.get('BCHAIN/HRATE')
Hash_Rate['Date'] = Hash_Rate.index
Name_Vec.append('Hash_Rate')
Hash_Rate.shape

(4559, 2)

In [181]:
#9. Bitcoin Cost Per Transaction
Bitcoin_Cost_Transaction = quandl.get('BCHAIN/CPTRA')
Bitcoin_Cost_Transaction['Date'] = Bitcoin_Cost_Transaction.index
Name_Vec.append('Bitcoin_Cost_Transaction')
Bitcoin_Cost_Transaction.shape

(4560, 2)

In [184]:
#10. Bitcoin Cost percentage of Transaction Volume
Bitcoin_Cost_percentage_of_Transaction_Volume = quandl.get('BCHAIN/CPTRV')
Bitcoin_Cost_percentage_of_Transaction_Volume['Date'] = Bitcoin_Cost_percentage_of_Transaction_Volume.index
Name_Vec.append('Bitcoin_Cost_percentage_of_Transaction_Volume')
Bitcoin_Cost_percentage_of_Transaction_Volume.shape

(4559, 2)

In [187]:
#11. Bitcoin Estimated Transaction Volume
Estimated_Transaction_Volume = quandl.get('BCHAIN/ETRAV')
Estimated_Transaction_Volume['Date'] = Estimated_Transaction_Volume.index
Name_Vec.append('Estimated_Transaction_Volume')
Estimated_Transaction_Volume.shape

(4559, 2)

In [190]:
#12. Bitcoin Total Output Volume
Total_Output_Volume = quandl.get('BCHAIN/TOUTV')
Total_Output_Volume['Date'] = Total_Output_Volume.index
Name_Vec.append('Total_Output_Volume')
Total_Output_Volume.shape

(4560, 2)

In [193]:
#13. Bitcoin Number of Transaction per Block
num_transaction_per_Block = quandl.get('BCHAIN/NTRBL')
num_transaction_per_Block['Date'] = num_transaction_per_Block.index
Name_Vec.append('num_transaction_per_Block')
num_transaction_per_Block.shape

(4560, 2)

In [196]:
#14. Bitcoin Number of Unique Addresses Used
num_of_unique_addresses = quandl.get('BCHAIN/NADDU')
num_of_unique_addresses['Date'] = num_of_unique_addresses.index
Name_Vec.append('num_of_unique_addresses')
num_of_unique_addresses.shape

(4560, 2)

In [199]:
#15. Bitcoin Number of Transaction
num_of_transaction = quandl.get('BCHAIN/NTRAN')
num_of_transaction['Date'] = num_of_transaction.index
Name_Vec.append('num_of_transaction')
num_of_transaction.shape

(4560, 2)

In [203]:
#16. Bitcoin Total Transaction Fees
Total_transaction_fees = quandl.get('BCHAIN/TRFEE')
Total_transaction_fees['Date'] = Total_transaction_fees.index
Name_Vec.append('Total_transaction_fees')
Total_transaction_fees.shape

(4560, 2)

In [205]:
#17. Total Bitcoins
Total_Bitcoins = quandl.get('BCHAIN/TOTBC')
Total_Bitcoins['Date'] = Total_Bitcoins.index
Name_Vec.append('Total_Bitcoins')
Total_Bitcoins.shape

(4560, 2)

In [208]:
#18.Bitcoin Median Transaction Confirmation Time
Median_transaction_confirmation_time = quandl.get('BCHAIN/ATRCT')
Median_transaction_confirmation_time['Date'] = Median_transaction_confirmation_time.index
Name_Vec.append('Median_transaction_confirmation_time')
Median_transaction_confirmation_time.shape

(4171, 2)

In [119]:
Median_transaction_confirmation_time

                Value
Date
2009-01-03   0.000000
2009-01-04   0.000000
2009-01-05   0.000000
2009-01-06   0.000000
2009-01-07   0.000000
...               ...
2021-06-23  15.850000
2021-06-24  16.700000
2021-06-25  12.445833
2021-06-26  16.858333
2021-06-27  17.816667

[4171 rows x 1 columns]

In [117]:
# 18 features
#Bitcoin Median Transaction Confirmation Time is the shortest

In [140]:
###Intergrate all features

In [ ]:
#1 Date_vec == Bitcoin_my_wallet_num_users vs Volume

In [143]:
Date_vec = []
for i in Bitcoin_my_wallet_num_users['Date']:
    for j in Volume['Date']:
        if i == j:
            Date_vec.append(i)

In [151]:
len(Date_vec)
a = Volume.loc[Date_vec, 'Value']

In [152]:
#2 Date_vec2 == Date_vec vs #3 Difficulty
Date_vec2 = []
for i in Date_vec:
    for j in Difficulty['Date']:
        if i == j:
            Date_vec2.append(i)

[Timestamp('2009-01-02 00:00:00'),
 Timestamp('2009-01-03 00:00:00'),
 Timestamp('2009-01-04 00:00:00'),
 Timestamp('2009-01-05 00:00:00'),
 Timestamp('2009-01-06 00:00:00'),
 Timestamp('2009-01-07 00:00:00'),
 Timestamp('2009-01-08 00:00:00'),
 Timestamp('2009-01-09 00:00:00'),
 Timestamp('2009-01-10 00:00:00'),
 Timestamp('2009-01-11 00:00:00'),
 Timestamp('2009-01-12 00:00:00'),
 Timestamp('2009-01-13 00:00:00'),
 Timestamp('2009-01-14 00:00:00'),
 Timestamp('2009-01-15 00:00:00'),
 Timestamp('2009-01-16 00:00:00'),
 Timestamp('2009-01-17 00:00:00'),
 Timestamp('2009-01-18 00:00:00'),
 Timestamp('2009-01-19 00:00:00'),
 Timestamp('2009-01-20 00:00:00'),
 Timestamp('2009-01-21 00:00:00'),
 Timestamp('2009-01-22 00:00:00'),
 Timestamp('2009-01-23 00:00:00'),
 Timestamp('2009-01-24 00:00:00'),
 Timestamp('2009-01-25 00:00:00'),
 Timestamp('2009-01-26 00:00:00'),
 Timestamp('2009-01-27 00:00:00'),
 Timestamp('2009-01-28 00:00:00'),
 Timestamp('2009-01-29 00:00:00'),
 Timestamp('2009-01-30 00:00:00'),
 Timestamp('2009-01-31 00:00:00'),
 Timestamp('2009-02-01 00:00:00'),
 Timestamp('2009-02-02 00:00:00'),
 Timestamp('2009-02-03 00:00:00'),
 Timestamp('2009-02-04 00:00:00'),
 Timestamp('2009-02-05 00:00:00'),
 Timestamp('2009-02-06 00:00:00'),
 Timestamp('2009-02-07 00:00:00'),
 Timestamp('2009-02-08 00:00:00'),
 Timestamp('2009-02-09 00:00:00'),
 Timestamp('2009-02-10 00:00:00'),
 Timestamp('2009-02-11 00:00:00'),
 Timestamp('2009-02-12 00:00:00'),
 Timestamp('2009-02-13 00:00:00'),
 Timestamp('2009-02-14 00:00:00'),
 Timestamp('2009-02-15 00:00:00'),
 Timestamp('2009-02-16 00:00:00'),
 Timestamp('2009-02-17 00:00:00'),
 Timestamp('2009-02-18 00:00:00'),
 Timestamp('2009-02-19 00:00:00'),
 Timestamp('2009-02-20 00:00:00'),
 Timestamp('2009-02-21 00:00:00'),
 Timestamp('2009-02-22 00:00:00'),
 Timestamp('2009-02-23 00:00:00'),
 Timestamp('2009-02-24 00:00:00'),
 Timestamp('2009-02-25 00:00:00'),
 Timestamp('2009-02-26 00:00:00'),
 Timestamp('2009-02-27 00:00:00'),
 Timestamp('2009-02-28 00:00:00'),
 Timestamp('2009-03-01 00:00:00'),
 Timestamp('2009-03-02 00:00:00'),
 Timestamp('2009-03-03 00:00:00'),
 Timestamp('2009-03-04 00:00:00'),
 Timestamp('2009-03-05 00:00:00'),
 Timestamp('2009-03-06 00:00:00'),
 Timestamp('2009-03-07 00:00:00'),
 Timestamp('2009-03-08 00:00:00'),
 Timestamp('2009-03-09 00:00:00'),
 Timestamp('2009-03-10 00:00:00'),
 Timestamp('2009-03-11 00:00:00'),
 Timestamp('2009-03-12 00:00:00'),
 Timestamp('2009-03-13 00:00:00'),
 Timestamp('2009-03-14 00:00:00'),
 Timestamp('2009-03-15 00:00:00'),
 Timestamp('2009-03-16 00:00:00'),
 Timestamp('2009-03-17 00:00:00'),
 Timestamp('2009-03-18 00:00:00'),
 Timestamp('2009-03-19 00:00:00'),
 Timestamp('2009-03-20 00:00:00'),
 Timestamp('2009-03-21 00:00:00'),
 Timestamp('2009-03-22 00:00:00'),
 Timestamp('2009-03-23 00:00:00'),
 Timestamp('2009-03-24 00:00:00'),
 Timestamp('2009-03-25 00:00:00'),
 Timestamp('2009-03-26 00:00:00'),
 Timestamp('2009-03-27 00:00:00'),
 Timestamp('2009-03-28 00:00:00'),
 Timestamp('2009-03-29 00:00:00'),
 Timestamp('2009-03-30 00:00:00'),
 Timestamp('2009-03-31 00:00:00'),
 Timestamp('2009-04-01 00:00:00'),
 Timestamp('2009-04-02 00:00:00'),
 Timestamp('2009-04-03 00:00:00'),
 Timestamp('2009-04-04 00:00:00'),
 Timestamp('2009-04-05 00:00:00'),
 Timestamp('2009-04-06 00:00:00'),
 Timestamp('2009-04-07 00:00:00'),
 Timestamp('2009-04-08 00:00:00'),
 Timestamp('2009-04-09 00:00:00'),
 Timestamp('2009-04-10 00:00:00'),
 Timestamp('2009-04-11 00:00:00'),
 Timestamp('2009-04-12 00:00:00'),
 Timestamp('2009-04-13 00:00:00'),
 Timestamp('2009-04-14 00:00:00'),
 Timestamp('2009-04-15 00:00:00'),
 Timestamp('2009-04-16 00:00:00'),
 Timestamp('2009-04-17 00:00:00'),
 Timestamp('2009-04-18 00:00:00'),
 Timestamp('2009-04-19 00:00:00'),
 Timestamp('2009-04-20 00:00:00'),
 Timestamp('2009-04-21 00:00:00'),
 Timestamp('2009-04-22 00:00:00'),
 Timestamp('2009-04-23 00:00:00'),
 Timestamp('2009-04-24 00:00:00'),
 Timestamp('2009-04-25 00:00:00'),
 Timestamp('2009-04-26 00:00:00'),
 Timestamp('2009-04-27 00:00:00'),
 Timestamp('2009-04-28 00:00:00'),
 Timestamp('2009-04-29 00:00:00'),
 Timestamp('2009-04-30 00:00:00'),
 Timestamp('2009-05-01 00:00:00'),
 Timestamp('2009-05-02 00:00:00'),
 Timestamp('2009-05-03 00:00:00'),
 Timestamp('2009-05-04 00:00:00'),
 Timestamp('2009-05-05 00:00:00'),
 Timestamp('2009-05-06 00:00:00'),
 Timestamp('2009-05-07 00:00:00'),
 Timestamp('2009-05-08 00:00:00'),
 Timestamp('2009-05-09 00:00:00'),
 Timestamp('2009-05-10 00:00:00'),
 Timestamp('2009-05-11 00:00:00'),
 Timestamp('2009-05-12 00:00:00'),
 Timestamp('2009-05-13 00:00:00'),
 Timestamp('2009-05-14 00:00:00'),
 Timestamp('2009-05-15 00:00:00'),
 Timestamp('2009-05-16 00:00:00'),
 Timestamp('2009-05-17 00:00:00'),
 Timestamp('2009-05-18 00:00:00'),
 Timestamp('2009-05-19 00:00:00'),
 Timestamp('2009-05-20 00:00:00'),
 Timestamp('2009-05-21 00:00:00'),
 Timestamp('2009-05-22 00:00:00'),
 Timestamp('2009-05-23 00:00:00'),
 Timestamp('2009-05-24 00:00:00'),
 Timestamp('2009-05-25 00:00:00'),
 Timestamp('2009-05-26 00:00:00'),
 Timestamp('2009-05-27 00:00:00'),
 Timestamp('2009-05-28 00:00:00'),
 Timestamp('2009-05-29 00:00:00'),
 Timestamp('2009-05-30 00:00:00'),
 Timestamp('2009-05-31 00:00:00'),
 Timestamp('2009-06-01 00:00:00'),
 Timestamp('2009-06-02 00:00:00'),
 Timestamp('2009-06-03 00:00:00'),
 Timestamp('2009-06-04 00:00:00'),
 Timestamp('2009-06-05 00:00:00'),
 Timestamp('2009-06-06 00:00:00'),
 Timestamp('2009-06-07 00:00:00'),
 Timestamp('2009-06-08 00:00:00'),
 Timestamp('2009-06-09 00:00:00'),
 Timestamp('2009-06-10 00:00:00'),
 Timestamp('2009-06-11 00:00:00'),
 Timestamp('2009-06-12 00:00:00'),
 Timestamp('2009-06-13 00:00:00'),
 Timestamp('2009-06-14 00:00:00'),
 Timestamp('2009-06-15 00:00:00'),
 Timestamp('2009-06-16 00:00:00'),
 Timestamp('2009-06-17 00:00:00'),
 Timestamp('2009-06-18 00:00:00'),
 Timestamp('2009-06-19 00:00:00'),
 Timestamp('2009-06-20 00:00:00'),
 Timestamp('2009-06-21 00:00:00'),
 Timestamp('2009-06-22 00:00:00'),
 Timestamp('2009-06-23 00:00:00'),
 Timestamp('2009-06-24 00:00:00'),
 Timestamp('2009-06-25 00:00:00'),
 Timestamp('2009-06-26 00:00:00'),
 Timestamp('2009-06-27 00:00:00'),
 Timestamp('2009-06-28 00:00:00'),
 Timestamp('2009-06-29 00:00:00'),
 Timestamp('2009-06-30 00:00:00'),
 Timestamp('2009-07-01 00:00:00'),
 Timestamp('2009-07-02 00:00:00'),
 Timestamp('2009-07-03 00:00:00'),
 Timestamp('2009-07-04 00:00:00'),
 Timestamp('2009-07-05 00:00:00'),
 Timestamp('2009-07-06 00:00:00'),
 Timestamp('2009-07-07 00:00:00'),
 Timestamp('2009-07-08 00:00:00'),
 Timestamp('2009-07-09 00:00:00'),
 Timestamp('2009-07-10 00:00:00'),
 Timestamp('2009-07-11 00:00:00'),
 Timestamp('2009-07-12 00:00:00'),
 Timestamp('2009-07-13 00:00:00'),
 Timestamp('2009-07-14 00:00:00'),
 Timestamp('2009-07-15 00:00:00'),
 Timestamp('2009-07-16 00:00:00'),
 Timestamp('2009-07-17 00:00:00'),
 Timestamp('2009-07-18 00:00:00'),
 Timestamp('2009-07-19 00:00:00'),
 Timestamp('2009-07-20 00:00:00'),
 Timestamp('2009-07-21 00:00:00'),
 Timestamp('2009-07-22 00:00:00'),
 Timestamp('2009-07-23 00:00:00'),
 Timestamp('2009-07-24 00:00:00'),
 Timestamp('2009-07-25 00:00:00'),
 Timestamp('2009-07-26 00:00:00'),
 Timestamp('2009-07-27 00:00:00'),
 Timestamp('2009-07-28 00:00:00'),
 Timestamp('2009-07-29 00:00:00'),
 Timestamp('2009-07-30 00:00:00'),
 Timestamp('2009-07-31 00:00:00'),
 Timestamp('2009-08-01 00:00:00'),
 Timestamp('2009-08-02 00:00:00'),
 Timestamp('2009-08-03 00:00:00'),
 Timestamp('2009-08-04 00:00:00'),
 Timestamp('2009-08-05 00:00:00'),
 Timestamp('2009-08-06 00:00:00'),
 Timestamp('2009-08-07 00:00:00'),
 Timestamp('2009-08-08 00:00:00'),
 Timestamp('2009-08-09 00:00:00'),
 Timestamp('2009-08-10 00:00:00'),
 Timestamp('2009-08-11 00:00:00'),
 Timestamp('2009-08-12 00:00:00'),
 Timestamp('2009-08-13 00:00:00'),
 Timestamp('2009-08-14 00:00:00'),
 Timestamp('2009-08-15 00:00:00'),
 Timestamp('2009-08-16 00:00:00'),
 Timestamp('2009-08-17 00:00:00'),
 Timestamp('2009-08-18 00:00:00'),
 Timestamp('2009-08-19 00:00:00'),
 Timestamp('2009-08-20 00:00:00'),
 Timestamp('2009-08-21 00:00:00'),
 Timestamp('2009-08-22 00:00:00'),
 Timestamp('2009-08-23 00:00:00'),
 Timestamp('2009-08-24 00:00:00'),
 Timestamp('2009-08-25 00:00:00'),
 Timestamp('2009-08-26 00:00:00'),
 Timestamp('2009-08-27 00:00:00'),
 Timestamp('2009-08-28 00:00:00'),
 Timestamp('2009-08-29 00:00:00'),
 Timestamp('2009-08-30 00:00:00'),
 Timestamp('2009-08-31 00:00:00'),
 Timestamp('2009-09-01 00:00:00'),
 Timestamp('2009-09-02 00:00:00'),
 Timestamp('2009-09-03 00:00:00'),
 Timestamp('2009-09-04 00:00:00'),
 Timestamp('2009-09-05 00:00:00'),
 Timestamp('2009-09-06 00:00:00'),
 Timestamp('2009-09-07 00:00:00'),
 Timestamp('2009-09-08 00:00:00'),
 Timestamp('2009-09-09 00:00:00'),
 Timestamp('2009-09-10 00:00:00'),
 Timestamp('2009-09-11 00:00:00'),
 Timestamp('2009-09-12 00:00:00'),
 Timestamp('2009-09-13 00:00:00'),
 Timestamp('2009-09-14 00:00:00'),
 Timestamp('2009-09-15 00:00:00'),
 Timestamp('2009-09-16 00:00:00'),
 Timestamp('2009-09-17 00:00:00'),
 Timestamp('2009-09-18 00:00:00'),
 Timestamp('2009-09-19 00:00:00'),
 Timestamp('2009-09-20 00:00:00'),
 Timestamp('2009-09-21 00:00:00'),
 Timestamp('2009-09-22 00:00:00'),
 Timestamp('2009-09-23 00:00:00'),
 Timestamp('2009-09-24 00:00:00'),
 Timestamp('2009-09-25 00:00:00'),
 Timestamp('2009-09-26 00:00:00'),
 Timestamp('2009-09-27 00:00:00'),
 Timestamp('2009-09-28 00:00:00'),
 Timestamp('2009-09-29 00:00:00'),
 Timestamp('2009-09-30 00:00:00'),
 Timestamp('2009-10-01 00:00:00'),
 Timestamp('2009-10-02 00:00:00'),
 Timestamp('2009-10-03 00:00:00'),
 Timestamp('2009-10-04 00:00:00'),
 Timestamp('2009-10-05 00:00:00'),
 Timestamp('2009-10-06 00:00:00'),
 Timestamp('2009-10-07 00:00:00'),
 Timestamp('2009-10-08 00:00:00'),
 Timestamp('2009-10-09 00:00:00'),
 Timestamp('2009-10-10 00:00:00'),
 Timestamp('2009-10-11 00:00:00'),
 Timestamp('2009-10-12 00:00:00'),
 Timestamp('2009-10-13 00:00:00'),
 Timestamp('2009-10-14 00:00:00'),
 Timestamp('2009-10-15 00:00:00'),
 Timestamp('2009-10-16 00:00:00'),
 Timestamp('2009-10-17 00:00:00'),
 Timestamp('2009-10-18 00:00:00'),
 Timestamp('2009-10-19 00:00:00'),
 Timestamp('2009-10-20 00:00:00'),
 Timestamp('2009-10-21 00:00:00'),
 Timestamp('2009-10-22 00:00:00'),
 Timestamp('2009-10-23 00:00:00'),
 Timestamp('2009-10-24 00:00:00'),
 Timestamp('2009-10-25 00:00:00'),
 Timestamp('2009-10-26 00:00:00'),
 Timestamp('2009-10-27 00:00:00'),
 Timestamp('2009-10-28 00:00:00'),
 Timestamp('2009-10-29 00:00:00'),
 Timestamp('2009-10-30 00:00:00'),
 Timestamp('2009-10-31 00:00:00'),
 Timestamp('2009-11-01 00:00:00'),
 Timestamp('2009-11-02 00:00:00'),
 Timestamp('2009-11-03 00:00:00'),
 Timestamp('2009-11-04 00:00:00'),
 Timestamp('2009-11-05 00:00:00'),
 Timestamp('2009-11-06 00:00:00'),
 Timestamp('2009-11-07 00:00:00'),
 Timestamp('2009-11-08 00:00:00'),
 Timestamp('2009-11-09 00:00:00'),
 Timestamp('2009-11-10 00:00:00'),
 Timestamp('2009-11-11 00:00:00'),
 Timestamp('2009-11-12 00:00:00'),
 Timestamp('2009-11-13 00:00:00'),
 Timestamp('2009-11-14 00:00:00'),
 Timestamp('2009-11-15 00:00:00'),
 Timestamp('2009-11-16 00:00:00'),
 Timestamp('2009-11-17 00:00:00'),
 Timestamp('2009-11-18 00:00:00'),
 Timestamp('2009-11-19 00:00:00'),
 Timestamp('2009-11-20 00:00:00'),
 Timestamp('2009-11-21 00:00:00'),
 Timestamp('2009-11-22 00:00:00'),
 Timestamp('2009-11-23 00:00:00'),
 Timestamp('2009-11-24 00:00:00'),
 Timestamp('2009-11-25 00:00:00'),
 Timestamp('2009-11-26 00:00:00'),
 Timestamp('2009-11-27 00:00:00'),
 Timestamp('2009-11-28 00:00:00'),
 Timestamp('2009-11-29 00:00:00'),
 Timestamp('2009-11-30 00:00:00'),
 Timestamp('2009-12-01 00:00:00'),
 Timestamp('2009-12-02 00:00:00'),
 Timestamp('2009-12-03 00:00:00'),
 Timestamp('2009-12-04 00:00:00'),
 Timestamp('2009-12-05 00:00:00'),
 Timestamp('2009-12-06 00:00:00'),
 Timestamp('2009-12-07 00:00:00'),
 Timestamp('2009-12-08 00:00:00'),
 Timestamp('2009-12-09 00:00:00'),
 Timestamp('2009-12-10 00:00:00'),
 Timestamp('2009-12-11 00:00:00'),
 Timestamp('2009-12-12 00:00:00'),
 Timestamp('2009-12-13 00:00:00'),
 Timestamp('2009-12-14 00:00:00'),
 Timestamp('2009-12-15 00:00:00'),
 Timestamp('2009-12-16 00:00:00'),
 Timestamp('2009-12-17 00:00:00'),
 Timestamp('2009-12-18 00:00:00'),
 Timestamp('2009-12-19 00:00:00'),
 Timestamp('2009-12-20 00:00:00'),
 Timestamp('2009-12-21 00:00:00'),
 Timestamp('2009-12-22 00:00:00'),
 Timestamp('2009-12-23 00:00:00'),
 Timestamp('2009-12-24 00:00:00'),
 Timestamp('2009-12-25 00:00:00'),
 Timestamp('2009-12-26 00:00:00'),
 Timestamp('2009-12-27 00:00:00'),
 Timestamp('2009-12-28 00:00:00'),
 Timestamp('2009-12-29 00:00:00'),
 Timestamp('2009-12-30 00:00:00'),
 Timestamp('2009-12-31 00:00:00'),
 Timestamp('2010-01-01 00:00:00'),
 Timestamp('2010-01-02 00:00:00'),
 Timestamp('2010-01-03 00:00:00'),
 Timestamp('2010-01-04 00:00:00'),
 Timestamp('2010-01-05 00:00:00'),
 Timestamp('2010-01-06 00:00:00'),
 Timestamp('2010-01-07 00:00:00'),
 Timestamp('2010-01-08 00:00:00'),
 Timestamp('2010-01-09 00:00:00'),
 Timestamp('2010-01-10 00:00:00'),
 Timestamp('2010-01-11 00:00:00'),
 Timestamp('2010-01-12 00:00:00'),
 Timestamp('2010-01-13 00:00:00'),
 Timestamp('2010-01-14 00:00:00'),
 Timestamp('2010-01-15 00:00:00'),
 Timestamp('2010-01-16 00:00:00'),
 Timestamp('2010-01-17 00:00:00'),
 Timestamp('2010-01-18 00:00:00'),
 Timestamp('2010-01-19 00:00:00'),
 Timestamp('2010-01-20 00:00:00'),
 Timestamp('2010-01-21 00:00:00'),
 Timestamp('2010-01-22 00:00:00'),
 Timestamp('2010-01-23 00:00:00'),
 Timestamp('2010-01-24 00:00:00'),
 Timestamp('2010-01-25 00:00:00'),
 Timestamp('2010-01-26 00:00:00'),
 Timestamp('2010-01-27 00:00:00'),
 Timestamp('2010-01-28 00:00:00'),
 Timestamp('2010-01-29 00:00:00'),
 Timestamp('2010-01-30 00:00:00'),
 Timestamp('2010-01-31 00:00:00'),
 Timestamp('2010-02-01 00:00:00'),
 Timestamp('2010-02-02 00:00:00'),
 Timestamp('2010-02-03 00:00:00'),
 Timestamp('2010-02-04 00:00:00'),
 Timestamp('2010-02-05 00:00:00'),
 Timestamp('2010-02-06 00:00:00'),
 Timestamp('2010-02-07 00:00:00'),
 Timestamp('2010-02-08 00:00:00'),
 Timestamp('2010-02-09 00:00:00'),
 Timestamp('2010-02-10 00:00:00'),
 Timestamp('2010-02-11 00:00:00'),
 Timestamp('2010-02-12 00:00:00'),
 Timestamp('2010-02-13 00:00:00'),
 Timestamp('2010-02-14 00:00:00'),
 Timestamp('2010-02-15 00:00:00'),
 Timestamp('2010-02-16 00:00:00'),
 Timestamp('2010-02-17 00:00:00'),
 Timestamp('2010-02-18 00:00:00'),
 Timestamp('2010-02-19 00:00:00'),
 Timestamp('2010-02-20 00:00:00'),
 Timestamp('2010-02-21 00:00:00'),
 Timestamp('2010-02-22 00:00:00'),
 Timestamp('2010-02-23 00:00:00'),
 Timestamp('2010-02-24 00:00:00'),
 Timestamp('2010-02-25 00:00:00'),
 Timestamp('2010-02-26 00:00:00'),
 Timestamp('2010-02-27 00:00:00'),
 Timestamp('2010-02-28 00:00:00'),
 Timestamp('2010-03-01 00:00:00'),
 Timestamp('2010-03-02 00:00:00'),
 Timestamp('2010-03-03 00:00:00'),
 Timestamp('2010-03-04 00:00:00'),
 Timestamp('2010-03-05 00:00:00'),
 Timestamp('2010-03-06 00:00:00'),
 Timestamp('2010-03-07 00:00:00'),
 Timestamp('2010-03-08 00:00:00'),
 Timestamp('2010-03-09 00:00:00'),
 Timestamp('2010-03-10 00:00:00'),
 Timestamp('2010-03-11 00:00:00'),
 Timestamp('2010-03-12 00:00:00'),
 Timestamp('2010-03-13 00:00:00'),
 Timestamp('2010-03-14 00:00:00'),
 Timestamp('2010-03-15 00:00:00'),
 Timestamp('2010-03-16 00:00:00'),
 Timestamp('2010-03-17 00:00:00'),
 Timestamp('2010-03-18 00:00:00'),
 Timestamp('2010-03-19 00:00:00'),
 Timestamp('2010-03-20 00:00:00'),
 Timestamp('2010-03-21 00:00:00'),
 Timestamp('2010-03-22 00:00:00'),
 Timestamp('2010-03-23 00:00:00'),
 Timestamp('2010-03-24 00:00:00'),
 Timestamp('2010-03-25 00:00:00'),
 Timestamp('2010-03-26 00:00:00'),
 Timestamp('2010-03-27 00:00:00'),
 Timestamp('2010-03-28 00:00:00'),
 Timestamp('2010-03-29 00:00:00'),
 Timestamp('2010-03-30 00:00:00'),
 Timestamp('2010-03-31 00:00:00'),
 Timestamp('2010-04-01 00:00:00'),
 Timestamp('2010-04-02 00:00:00'),
 Timestamp('2010-04-03 00:00:00'),
 Timestamp('2010-04-04 00:00:00'),
 Timestamp('2010-04-05 00:00:00'),
 Timestamp('2010-04-06 00:00:00'),
 Timestamp('2010-04-07 00:00:00'),
 Timestamp('2010-04-08 00:00:00'),
 Timestamp('2010-04-09 00:00:00'),
 Timestamp('2010-04-10 00:00:00'),
 Timestamp('2010-04-11 00:00:00'),
 Timestamp('2010-04-12 00:00:00'),
 Timestamp('2010-04-13 00:00:00'),
 Timestamp('2010-04-14 00:00:00'),
 Timestamp('2010-04-15 00:00:00'),
 Timestamp('2010-04-16 00:00:00'),
 Timestamp('2010-04-17 00:00:00'),
 Timestamp('2010-04-18 00:00:00'),
 Timestamp('2010-04-19 00:00:00'),
 Timestamp('2010-04-20 00:00:00'),
 Timestamp('2010-04-21 00:00:00'),
 Timestamp('2010-04-22 00:00:00'),
 Timestamp('2010-04-23 00:00:00'),
 Timestamp('2010-04-24 00:00:00'),
 Timestamp('2010-04-25 00:00:00'),
 Timestamp('2010-04-26 00:00:00'),
 Timestamp('2010-04-27 00:00:00'),
 Timestamp('2010-04-28 00:00:00'),
 Timestamp('2010-04-29 00:00:00'),
 Timestamp('2010-04-30 00:00:00'),
 Timestamp('2010-05-01 00:00:00'),
 Timestamp('2010-05-02 00:00:00'),
 Timestamp('2010-05-03 00:00:00'),
 Timestamp('2010-05-04 00:00:00'),
 Timestamp('2010-05-05 00:00:00'),
 Timestamp('2010-05-06 00:00:00'),
 Timestamp('2010-05-07 00:00:00'),
 Timestamp('2010-05-08 00:00:00'),
 Timestamp('2010-05-09 00:00:00'),
 Timestamp('2010-05-10 00:00:00'),
 Timestamp('2010-05-11 00:00:00'),
 Timestamp('2010-05-12 00:00:00'),
 Timestamp('2010-05-13 00:00:00'),
 Timestamp('2010-05-14 00:00:00'),
 Timestamp('2010-05-15 00:00:00'),
 Timestamp('2010-05-16 00:00:00'),
 Timestamp('2010-05-17 00:00:00'),
 Timestamp('2010-05-18 00:00:00'),
 Timestamp('2010-05-19 00:00:00'),
 Timestamp('2010-05-20 00:00:00'),
 Timestamp('2010-05-21 00:00:00'),
 Timestamp('2010-05-22 00:00:00'),
 Timestamp('2010-05-23 00:00:00'),
 Timestamp('2010-05-24 00:00:00'),
 Timestamp('2010-05-25 00:00:00'),
 Timestamp('2010-05-26 00:00:00'),
 Timestamp('2010-05-27 00:00:00'),
 Timestamp('2010-05-28 00:00:00'),
 Timestamp('2010-05-29 00:00:00'),
 Timestamp('2010-05-30 00:00:00'),
 Timestamp('2010-05-31 00:00:00'),
 Timestamp('2010-06-01 00:00:00'),
 Timestamp('2010-06-02 00:00:00'),
 Timestamp('2010-06-03 00:00:00'),
 Timestamp('2010-06-04 00:00:00'),
 Timestamp('2010-06-05 00:00:00'),
 Timestamp('2010-06-06 00:00:00'),
 Timestamp('2010-06-07 00:00:00'),
 Timestamp('2010-06-08 00:00:00'),
 Timestamp('2010-06-09 00:00:00'),
 Timestamp('2010-06-10 00:00:00'),
 Timestamp('2010-06-11 00:00:00'),
 Timestamp('2010-06-12 00:00:00'),
 Timestamp('2010-06-13 00:00:00'),
 Timestamp('2010-06-14 00:00:00'),
 Timestamp('2010-06-15 00:00:00'),
 Timestamp('2010-06-16 00:00:00'),
 Timestamp('2010-06-17 00:00:00'),
 Timestamp('2010-06-18 00:00:00'),
 Timestamp('2010-06-19 00:00:00'),
 Timestamp('2010-06-20 00:00:00'),
 Timestamp('2010-06-21 00:00:00'),
 Timestamp('2010-06-22 00:00:00'),
 Timestamp('2010-06-23 00:00:00'),
 Timestamp('2010-06-24 00:00:00'),
 Timestamp('2010-06-25 00:00:00'),
 Timestamp('2010-06-26 00:00:00'),
 Timestamp('2010-06-27 00:00:00'),
 Timestamp('2010-06-28 00:00:00'),
 Timestamp('2010-06-29 00:00:00'),
 Timestamp('2010-06-30 00:00:00'),
 Timestamp('2010-07-01 00:00:00'),
 Timestamp('2010-07-02 00:00:00'),
 Timestamp('2010-07-03 00:00:00'),
 Timestamp('2010-07-04 00:00:00'),
 Timestamp('2010-07-05 00:00:00'),
 Timestamp('2010-07-06 00:00:00'),
 Timestamp('2010-07-07 00:00:00'),
 Timestamp('2010-07-08 00:00:00'),
 Timestamp('2010-07-09 00:00:00'),
 Timestamp('2010-07-10 00:00:00'),
 Timestamp('2010-07-11 00:00:00'),
 Timestamp('2010-07-12 00:00:00'),
 Timestamp('2010-07-13 00:00:00'),
 Timestamp('2010-07-14 00:00:00'),
 Timestamp('2010-07-15 00:00:00'),
 Timestamp('2010-07-16 00:00:00'),
 Timestamp('2010-07-17 00:00:00'),
 Timestamp('2010-07-18 00:00:00'),
 Timestamp('2010-07-19 00:00:00'),
 Timestamp('2010-07-20 00:00:00'),
 Timestamp('2010-07-21 00:00:00'),
 Timestamp('2010-07-22 00:00:00'),
 Timestamp('2010-07-23 00:00:00'),
 Timestamp('2010-07-24 00:00:00'),
 Timestamp('2010-07-25 00:00:00'),
 Timestamp('2010-07-26 00:00:00'),

In [154]:
len(Date_vec2)

4527

In [158]:
#3 Date_vec3 = Date_vec2 vs #4 wallet_num_transaction
Date_vec3 = []
for i in Date_vec2:
    for j in wallet_num_transaction['Date']:
        if i == j:
            Date_vec3.append(i)

In [160]:
len(Date_vec3)

4493

In [ ]:
#4 Date_vec4 = Date_vec3 vs #5 Bitcoin My Wallet Transaction Volume

In [167]:
Date_vec4 = []
for i in Date_vec3:
    for j in wallet_transaction_volume['Date']:
        if i == j:
            Date_vec4.append(i)

In [168]:
len(Date_vec4)

4493

In [173]:
#5 Date_vec5 = Date_vec4 vs #6 Bitcoin Avg Block Size
Date_vec5 = []
for i in Date_vec4:
    for j in Bitcoin_Avg_Block_Size['Date']:
        if i == j:
            Date_vec5.append(i)

In [174]:
len(Date_vec5)

4493

In [176]:
#6 Date_vec6 = Date_vec5 vs #7 Bitcoin Miners Revenue
Date_vec6 = []
for i in Date_vec5:
    for j in Miners_Revenue['Date']:
        if i == j:
            Date_vec6.append(i)

In [177]:
len(Date_vec6)

4493

In [179]:
#Date_vec7 = Date_vec6 vs #8  Hash_Rate
Date_vec7 = []
for i in Date_vec6:
    for j in Hash_Rate['Date']:
        if i == j:
            Date_vec7.append(i)

In [180]:
len(Date_vec7)

4492

In [182]:
#Date_vec8 = Date_vec7 vs #9
Date_vec8 = []
for i in Date_vec7:
    for j in Bitcoin_Cost_Transaction['Date']:
        if i == j:
            Date_vec8.append(i)

In [183]:
len(Date_vec8)

4492

In [185]:
#Date_vec9 = Date_vec8 vs #10 Bitcoin_Cost_percentage_of_Transaction_Volume
Date_vec9 = []
for i in Date_vec8:
    for j in Bitcoin_Cost_percentage_of_Transaction_Volume['Date']:
        if i == j:
            Date_vec9.append(i)

In [186]:
len(Date_vec9)

4492

In [188]:
#Date_vec10 = Date_vec9 vs #11 Estimated_Transaction_Volume
Date_vec10 = []
for i in Date_vec9:
    for j in Estimated_Transaction_Volume['Date']:
        if i == j:
            Date_vec10.append(i)

In [189]:
len(Date_vec10)

4492

In [191]:
#Date_vec11 = Date_vec10 vs #12 Total_Output_Volume
Date_vec11 = []
for i in Date_vec10:
    for j in Total_Output_Volume['Date']:
        if i == j:
            Date_vec11.append(i)

In [192]:
len(Date_vec11)

4492

In [194]:
#Date_vec12 = Date_vec11 vs #13 num_transaction_per_Block
Date_vec12 = []
for i in Date_vec11:
    for j in num_transaction_per_Block['Date']:
        if i == j:
            Date_vec12.append(i)

In [195]:
len(Date_vec12)

4492

In [197]:
#Date_vec13 = Date_vec12 vs #14 num_of_unique_addresses
Date_vec13 = []
for i in Date_vec12:
    for j in num_of_unique_addresses['Date']:
        if i == j:
            Date_vec13.append(i)

In [198]:
len(Date_vec13)

4492

In [200]:
#Date_vec14 = Date_vec13 vs #15 num_of_transaction
Date_vec14 = []
for i in Date_vec13:
    for j in num_of_transaction['Date']:
        if i == j:
            Date_vec14.append(i)

In [201]:
len(Date_vec14)

4492

In [204]:
#Date_vec15 = Date_vec14 vs #16 Total_transaction_fees
Date_vec15 = []
for i in Date_vec14:
    for j in Total_transaction_fees['Date']:
        if i == j:
            Date_vec15.append(i)

In [206]:
len(Date_vec15)

4492

In [207]:
#Date_vec16 = Date_vec15 vs #17 Total_Bitcoins
Date_vec16 = []
for i in Date_vec15:
    for j in Total_Bitcoins['Date']:
        if i == j:
            Date_vec16.append(i)

In [209]:
len(Date_vec16)

4492

In [210]:
#Date_vec17 = Date_vec16 vs #18 Median_transaction_confirmation_time
Date_vec17 = []
for i in Date_vec16:
    for j in Median_transaction_confirmation_time['Date']:
        if i == j:
            Date_vec17.append(i)

In [211]:
len(Date_vec17)

4126

In [214]:
working_place = os.getcwd()
working_place

'/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC'

In [222]:
#### Mergning Data
Data_Collection = pd.DataFrame()

In [225]:
Data_Collection['Bitcoin_my_wallet_num_users'] = Bitcoin_my_wallet_num_users.loc[Date_vec17,'Value']
Data_Collection['Volume'] = Volume.loc[Date_vec17, 'Value']
Data_Collection['Difficulty'] = Difficulty.loc[Date_vec17, 'Value']
Data_Collection['wallet_num_transaction'] = wallet_num_transaction.loc[Date_vec17, 'Value']
Data_Collection ['wallet_transaction_volume']= wallet_transaction_volume.loc[Date_vec17, 'Value']
Data_Collection['Bitcoin_Avg_Block_Size'] = Bitcoin_Avg_Block_Size.loc[Date_vec17, 'Value']
Data_Collection['Miners_Revenue'] = Miners_Revenue.loc[Date_vec17, 'Value']
Data_Collection['Hash_Rate'] = Hash_Rate.loc[Date_vec17, 'Value']
Data_Collection['Bitcoin_Cost_Transaction'] = Bitcoin_Cost_Transaction.loc[Date_vec17, 'Value']
Data_Collection['Bitcoin_Cost_percentage_of_Transaction_Volume'] = Bitcoin_Cost_percentage_of_Transaction_Volume.loc[Date_vec17, 'Value']
Data_Collection['Estimated_Transaction_Volume'] = Estimated_Transaction_Volume.loc[Date_vec17, 'Value']
Data_Collection['Total_Output_Volume'] = Total_Output_Volume.loc[Date_vec17, 'Value']
Data_Collection['num_transaction_per_Block'] = num_transaction_per_Block.loc[Date_vec17, 'Value']
Data_Collection['num_of_unique_addresses'] = num_of_unique_addresses.loc[Date_vec17, 'Value']
Data_Collection ['num_of_transaction'] = num_of_transaction.loc[Date_vec17, 'Value'] 
Data_Collection['Total_transaction_fees'] = Total_transaction_fees.loc[Date_vec17, 'Value']
Data_Collection['Total_Bitcoins']= Total_Bitcoins.loc[Date_vec17, 'Value']
Data_Collection['Median_transaction_confirmation_time'] = Median_transaction_confirmation_time.loc[Date_vec17, 'Value']

In [226]:
Data_Collection

,Bitcoin_my_wallet_num_users,Volume,Difficulty,wallet_num_transaction,wallet_transaction_volume,Bitcoin_Avg_Block_Size,Miners_Revenue,Hash_Rate,Bitcoin_Cost_Transaction,Bitcoin_Cost_percentage_of_Transaction_Volume,Estimated_Transaction_Volume,Total_Output_Volume,num_transaction_per_Block,num_of_unique_addresses,num_of_transaction,Total_transaction_fees,Total_Bitcoins,Median_transaction_confirmation_time
Date,,,,,,,,,,,,,,,,,,
2009-01-03,2.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.0,0.0,0.000000,50.00,0.000000
2009-01-04,2.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.0,0.0,0.000000,50.00,0.000000
2009-01-05,2.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.0,0.0,0.000000,50.00,0.000000
2009-01-06,2.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.0,0.0,0.000000,50.00,0.000000
2009-01-07,2.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1.000000,0.0,0.0,0.000000,50.00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-11,73952242.0,6.198308e+08,2.104773e+13,70810.0,18752.191114,1.401894,2.575379e+07,1.098603e+08,118.954072,0.735462,94723.611050,1.463831e+06,2061.923810,616007.0,216502.0,40.707472,18732506.25,12.633333
2021-06-12,73978203.0,4.181923e+08,2.104773e+13,55832.0,17967.657992,1.489760,3.118978e+07,1.381101e+08,139.888315,1.448210,59967.976659,1.009991e+06,1687.681818,584529.0,222774.0,35.490808,18733218.75,10.433333
2021-06-13,74021567.0,4.009877e+08,2.083657e+13,51233.0,19595.292437,1.174924,3.138211e+07,1.367245e+08,166.955415,2.038138,42109.398620,1.183322e+06,1417.409091,480484.0,187098.0,23.211976,18734081.25,8.145833
2021-06-14,74052123.0,4.964213e+08,1.993279e+13,73108.0,16377.869947,1.263461,3.642130e+07,1.337667e+08,148.213136,0.732347,125065.749571,1.487002e+06,1795.674074,624698.0,242416.0,37.661281,18735087.50,9.275000
2021-06-15,74063489.0,7.734807e+08,1.993279e+13,75832.0,23715.551072,1.294162,3.446505e+07,1.298032e+08,142.499415,0.844723,101585.652417,1.403796e+06,1846.267176,677276.0,241861.0,38.742437,18735756.25,10.216667

In [234]:
#######06/29/2021
## Clean Data, Set up Y
Data_Collection.astype(bool).sum(axis=0)

Bitcoin_my_wallet_num_users                      4126
Volume                                           3235
Difficulty                                       4121
wallet_num_transaction                           2928
wallet_transaction_volume                        2150
Bitcoin_Avg_Block_Size                           4121
Miners_Revenue                                   3535
Hash_Rate                                        4121
Bitcoin_Cost_Transaction                         3535
Bitcoin_Cost_percentage_of_Transaction_Volume    3866
Estimated_Transaction_Volume                     3864
Total_Output_Volume                              4121
num_transaction_per_Block                        4126
num_of_unique_addresses                          4121
num_of_transaction                               4121
Total_transaction_fees                           3518
Total_Bitcoins                                   4126
Median_transaction_confirmation_time             3063
dtype: int64

(2991, 18)

In [287]:
# Modification Step I: Start Date: 02/22/2021 )(1147 - 2)
#1145 : end
New_Data_Collection1 = Data_Collection.iloc[1145 : , :]
New_Data_Collection1.astype(bool).sum(axis=0)

Bitcoin_my_wallet_num_users                      2981
Volume                                           2865
Difficulty                                       2981
wallet_num_transaction                           2926
wallet_transaction_volume                        2148
Bitcoin_Avg_Block_Size                           2981
Miners_Revenue                                   2981
Hash_Rate                                        2981
Bitcoin_Cost_Transaction                         2981
Bitcoin_Cost_percentage_of_Transaction_Volume    2981
Estimated_Transaction_Volume                     2981
Total_Output_Volume                              2981
num_transaction_per_Block                        2981
num_of_unique_addresses                          2981
num_of_transaction                               2981
Total_transaction_fees                           2981
Total_Bitcoins                                   2981
Median_transaction_confirmation_time             2981
dtype: int64

In [288]:
New_Data_Collection1

,Bitcoin_my_wallet_num_users,Volume,Difficulty,wallet_num_transaction,wallet_transaction_volume,Bitcoin_Avg_Block_Size,Miners_Revenue,Hash_Rate,Bitcoin_Cost_Transaction,Bitcoin_Cost_percentage_of_Transaction_Volume,Estimated_Transaction_Volume,Total_Output_Volume,num_transaction_per_Block,num_of_unique_addresses,num_of_transaction,Total_transaction_fees,Total_Bitcoins,Median_transaction_confirmation_time
Date,,,,,,,,,,,,,,,,,,
2012-02-22,2108.0,6.817477e+05,1.376302e+06,0.0,0.000000,0.019584,3.859483e+04,1.149395e+01,5.149410,6.705325,125333.000000,8.101284e+05,45.245283,13080.0,7194.0,3.413929,8407200.00,12.050000
2012-02-23,2159.0,0.000000e+00,1.376302e+06,4.0,0.000000,0.023000,3.770470e+04,1.149395e+01,5.234582,4.330156,167523.000000,6.920325e+05,36.000000,12673.0,7203.0,4.334781,8414450.00,12.400000
2012-02-24,2159.0,3.385065e+05,1.376302e+06,16.0,255.640543,0.018101,4.235478e+04,1.142553e+01,6.429080,3.911625,195684.936629,5.232521e+05,43.000000,12250.0,6588.0,4.265741,8414250.00,9.816667
2012-02-25,2170.0,3.906573e+05,1.376302e+06,11.0,329.648517,0.018166,5.611210e+04,1.039929e+01,7.833603,8.508754,89343.000000,3.304846e+05,38.218182,10278.0,6306.0,3.122961,8430400.00,8.983333
2012-02-26,2213.0,0.000000e+00,1.376302e+06,11.0,0.000000,0.018256,4.031040e+04,1.039929e+01,6.225544,8.609758,91803.000000,3.471264e+05,47.000000,11131.0,6475.0,4.783724,8438300.00,11.116667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-11,73952242.0,6.198308e+08,2.104773e+13,70810.0,18752.191114,1.401894,2.575379e+07,1.098603e+08,118.954072,0.735462,94723.611050,1.463831e+06,2061.923810,616007.0,216502.0,40.707472,18732506.25,12.633333
2021-06-12,73978203.0,4.181923e+08,2.104773e+13,55832.0,17967.657992,1.489760,3.118978e+07,1.381101e+08,139.888315,1.448210,59967.976659,1.009991e+06,1687.681818,584529.0,222774.0,35.490808,18733218.75,10.433333
2021-06-13,74021567.0,4.009877e+08,2.083657e+13,51233.0,19595.292437,1.174924,3.138211e+07,1.367245e+08,166.955415,2.038138,42109.398620,1.183322e+06,1417.409091,480484.0,187098.0,23.211976,18734081.25,8.145833
2021-06-14,74052123.0,4.964213e+08,1.993279e+13,73108.0,16377.869947,1.263461,3.642130e+07,1.337667e+08,148.213136,0.732347,125065.749571,1.487002e+06,1795.674074,624698.0,242416.0,37.661281,18735087.50,9.275000
2021-06-15,74063489.0,7.734807e+08,1.993279e+13,75832.0,23715.551072,1.294162,3.446505e+07,1.298032e+08,142.499415,0.844723,101585.652417,1.403796e+06,1846.267176,677276.0,241861.0,38.742437,18735756.25,10.216667

In [289]:
# Modification Step II: Get rid of Wallet_Transaction_Volume
del New_Data_Collection1['wallet_transaction_volume']

In [290]:
New_Data_Collection1.shape

(2981, 17)

In [291]:
Final_Data_Collection = New_Data_Collection1.fillna(method = 'ffill')
Final_Data_Collection = New_Data_Collection1.dropna()
Final_Data_Collection.isnull().sum()

Bitcoin_my_wallet_num_users                      0
Volume                                           0
Difficulty                                       0
wallet_num_transaction                           0
Bitcoin_Avg_Block_Size                           0
Miners_Revenue                                   0
Hash_Rate                                        0
Bitcoin_Cost_Transaction                         0
Bitcoin_Cost_percentage_of_Transaction_Volume    0
Estimated_Transaction_Volume                     0
Total_Output_Volume                              0
num_transaction_per_Block                        0
num_of_unique_addresses                          0
num_of_transaction                               0
Total_transaction_fees                           0
Total_Bitcoins                                   0
Median_transaction_confirmation_time             0
dtype: int64

In [292]:
#Modification Step III: Get rid of the 0 in Volume & wallet_num_transaction
volume_vec = []
j = 0
for i in Final_Data_Collection['Volume']:
    if i == 0:
        a = (Final_Data_Collection['Volume'][j-1] + Final_Data_Collection['Volume'][j+1]) / 2
        volume_vec.append(a)
    else:
        volume_vec.append(i)
    j = j + 1
    
Final_Data_Collection['Volume'] = volume_vec

#2.
wallet_num_trans_vec = []
j = 0
for i in Final_Data_Collection['wallet_num_transaction']:
    if i == 0:
        a = (Final_Data_Collection['wallet_num_transaction'][j - 1] + Final_Data_Collection['wallet_num_transaction'][j + 1]) / 2
        wallet_num_trans_vec.append(a)
    else:
        wallet_num_trans_vec.append(i)
    j = j + 1
    
Final_Data_Collection['wallet_num_transaction'] = wallet_num_trans_vec

In [293]:
Final_Data_Collection.astype(bool).sum(axis=0)

Bitcoin_my_wallet_num_users                      2981
Volume                                           2981
Difficulty                                       2981
wallet_num_transaction                           2981
Bitcoin_Avg_Block_Size                           2981
Miners_Revenue                                   2981
Hash_Rate                                        2981
Bitcoin_Cost_Transaction                         2981
Bitcoin_Cost_percentage_of_Transaction_Volume    2981
Estimated_Transaction_Volume                     2981
Total_Output_Volume                              2981
num_transaction_per_Block                        2981
num_of_unique_addresses                          2981
num_of_transaction                               2981
Total_transaction_fees                           2981
Total_Bitcoins                                   2981
Median_transaction_confirmation_time             2981
dtype: int64

In [294]:
####### This is our Xs table (could alter it if Date for Price is not ideal)
Final_Data_Collection.to_csv(('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/FinalDataCollection.csv'))

In [295]:
###### Start collecting Y (Bitcoin Price) BCHAIN/MKPRU
Bitcoin_Price = quandl.get('BCHAIN/MKPRU')
Bitcoin_Price['Date'] = Bitcoin_Price.index

New_Date_Table = pd.DataFrame()
New_Date_Table['Date'] = Final_Data_Collection.index

# Date_vec18 == Final_Data_Collection vs Bitcoin Price
Date_vec18 = []
for i in New_Date_Table['Date']:
    for j in Bitcoin_Price['Date']:
        if i == j:
            Date_vec18.append(i)

In [297]:
Price_Table = pd.DataFrame()
Price_Table['Bitcoin_Price'] = Bitcoin_Price.loc[Date_vec18, 'Value']
len(Date_vec8)

2981

In [299]:
Price_Table.astype(bool).sum(axis=0)

Bitcoin_Price    2981
dtype: int64

In [300]:
#### Start Classifying Y (>=0.1, <0.1 and >0, <=0 )
Price_Table['Growth'] = (Price_Table['Bitcoin_Price'].shift(-1) - Price_Table['Bitcoin_Price'])/Price_Table['Bitcoin_Price']

In [301]:
Price_Table

            Bitcoin_Price    Growth
Date
2012-02-22        4.92481 -0.059862
2012-02-23        4.63000  0.095032
2012-02-24        5.07000 -0.013663
2012-02-25        5.00073  0.009853
2012-02-26        5.05000 -0.009901
...                   ...       ...
2021-06-11    36704.57000  0.016581
2021-06-12    37313.18000 -0.048730
2021-06-13    35494.90000  0.100632
2021-06-14    39066.82000  0.037346
2021-06-15    40525.80000       NaN

[2981 rows x 2 columns]

In [302]:
class_vec = []

for i in Price_Table['Growth']:
    if i >= 0.1:#good 
        class_vec.append(1)
    elif i <= 0:#bad
        class_vec.append(3)
    else: #Average and NaN
        class_vec.append(2)

In [303]:
Price_Table['Class'] = class_vec

In [310]:
Price_Table
###This is our Y Table. Y value is the class column.

            Bitcoin_Price    Growth  Class
Date
2012-02-22        4.92481 -0.059862      3
2012-02-23        4.63000  0.095032      2
2012-02-24        5.07000 -0.013663      3
2012-02-25        5.00073  0.009853      2
2012-02-26        5.05000 -0.009901      3
...                   ...       ...    ...
2021-06-11    36704.57000  0.016581      2
2021-06-12    37313.18000 -0.048730      3
2021-06-13    35494.90000  0.100632      1
2021-06-14    39066.82000  0.037346      2
2021-06-15    40525.80000       NaN      2

[2981 rows x 3 columns]

In [304]:
Price_Table.to_csv('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/Price.csv')

In [321]:
### ADD Y (Classes) to Total_Data_Collection
Final_Data_Collection['Class'] = Price_Table['Class']
Final_Data_Collection.to_csv(('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/FinalDataCollection.csv'))

In [322]:
Final_Data_Collection

,Bitcoin_my_wallet_num_users,Volume,Difficulty,wallet_num_transaction,Bitcoin_Avg_Block_Size,Miners_Revenue,Hash_Rate,Bitcoin_Cost_Transaction,Bitcoin_Cost_percentage_of_Transaction_Volume,Estimated_Transaction_Volume,Total_Output_Volume,num_transaction_per_Block,num_of_unique_addresses,num_of_transaction,Total_transaction_fees,Total_Bitcoins,Median_transaction_confirmation_time,Class
Date,,,,,,,,,,,,,,,,,,
2012-02-22,2108.0,6.817477e+05,1.376302e+06,37918.0,0.019584,3.859483e+04,1.149395e+01,5.149410,6.705325,125333.000000,8.101284e+05,45.245283,13080.0,7194.0,3.413929,8407200.00,12.050000,3
2012-02-23,2159.0,5.101271e+05,1.376302e+06,4.0,0.023000,3.770470e+04,1.149395e+01,5.234582,4.330156,167523.000000,6.920325e+05,36.000000,12673.0,7203.0,4.334781,8414450.00,12.400000,2
2012-02-24,2159.0,3.385065e+05,1.376302e+06,16.0,0.018101,4.235478e+04,1.142553e+01,6.429080,3.911625,195684.936629,5.232521e+05,43.000000,12250.0,6588.0,4.265741,8414250.00,9.816667,3
2012-02-25,2170.0,3.906573e+05,1.376302e+06,11.0,0.018166,5.611210e+04,1.039929e+01,7.833603,8.508754,89343.000000,3.304846e+05,38.218182,10278.0,6306.0,3.122961,8430400.00,8.983333,2
2012-02-26,2213.0,3.302660e+05,1.376302e+06,11.0,0.018256,4.031040e+04,1.039929e+01,6.225544,8.609758,91803.000000,3.471264e+05,47.000000,11131.0,6475.0,4.783724,8438300.00,11.116667,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-11,73952242.0,6.198308e+08,2.104773e+13,70810.0,1.401894,2.575379e+07,1.098603e+08,118.954072,0.735462,94723.611050,1.463831e+06,2061.923810,616007.0,216502.0,40.707472,18732506.25,12.633333,2
2021-06-12,73978203.0,4.181923e+08,2.104773e+13,55832.0,1.489760,3.118978e+07,1.381101e+08,139.888315,1.448210,59967.976659,1.009991e+06,1687.681818,584529.0,222774.0,35.490808,18733218.75,10.433333,3
2021-06-13,74021567.0,4.009877e+08,2.083657e+13,51233.0,1.174924,3.138211e+07,1.367245e+08,166.955415,2.038138,42109.398620,1.183322e+06,1417.409091,480484.0,187098.0,23.211976,18734081.25,8.145833,1
2021-06-14,74052123.0,4.964213e+08,1.993279e+13,73108.0,1.263461,3.642130e+07,1.337667e+08,148.213136,0.732347,125065.749571,1.487002e+06,1795.674074,624698.0,242416.0,37.661281,18735087.50,9.275000,2
2021-06-15,74063489.0,7.734807e+08,1.993279e+13,75832.0,1.294162,3.446505e+07,1.298032e+08,142.499415,0.844723,101585.652417,1.403796e+06,1846.267176,677276.0,241861.0,38.742437,18735756.25,10.216667,2

In [328]:
len(Price_Table)

2981

In [ ]:
#Create a randomly generated table
#Start picking Traning Set, Testing set and CV set

In [326]:
random_index = random.sample(range(0,len(Price_Table)),len(Price_Table)) #randomly generate numbers

In [329]:
len(random_index)

2981

In [330]:
Random_Data = pd.DataFrame()
Random_Data = Final_Data_Collection.iloc[random_index,:]

,Bitcoin_my_wallet_num_users,Volume,Difficulty,wallet_num_transaction,Bitcoin_Avg_Block_Size,Miners_Revenue,Hash_Rate,Bitcoin_Cost_Transaction,Bitcoin_Cost_percentage_of_Transaction_Volume,Estimated_Transaction_Volume,Total_Output_Volume,num_transaction_per_Block,num_of_unique_addresses,num_of_transaction,Total_transaction_fees,Total_Bitcoins,Median_transaction_confirmation_time,Class
Date,,,,,,,,,,,,,,,,,,
2020-08-21,52845759.0,9.674630e+07,1.694780e+13,107827.0,1.344397,1.298833e+07,1.305844e+08,41.325023,0.856408,129046.707856,1.495714e+06,2027.722581,675988.0,314297.0,136.108508,18467206.25,11.725000,3
2012-07-06,11698.0,1.983366e+05,1.751455e+06,2008.0,0.068160,5.926606e+04,1.480110e+01,2.333769,5.300868,161200.000000,4.379832e+06,154.296774,23077.0,23916.0,16.384672,9399750.00,11.650000,3
2021-01-01,63530742.0,6.065241e+08,1.859959e+13,89018.0,1.352233,2.906805e+07,1.377640e+08,111.931054,0.669276,148420.304251,1.603396e+06,1732.080537,609741.0,258080.0,48.942701,18587787.50,10.816667,2
2017-02-11,11922903.0,1.076439e+07,4.221706e+11,71978.0,0.963661,1.792077e+06,2.917084e+06,7.074184,1.143913,162125.913611,1.418142e+06,1889.827338,474676.0,262686.0,117.080010,16157775.00,17.158333,2
2013-07-12,349434.0,3.785155e+06,2.616288e+07,7372.0,0.123121,3.647810e+05,1.963851e+02,9.048719,1.396064,285190.208023,8.812012e+05,239.000000,57072.0,40313.0,25.135946,11409975.00,8.583333,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-04-25,240714.0,3.293561e+07,8.974296e+06,9088.0,0.151687,5.898643e+05,7.673172e+01,10.433983,1.553937,296822.197538,1.223972e+06,357.000000,74621.0,56533.0,50.847138,11076050.00,7.483333,3
2016-04-10,6784740.0,9.701992e+06,1.668515e+11,67535.0,0.553300,1.849715e+06,1.443197e+06,9.787420,2.195772,199611.000000,1.926492e+06,1080.658960,320083.0,186954.0,33.253399,15417250.00,7.033333,3
2017-02-12,11943593.0,1.475350e+07,4.221706e+11,65338.0,0.867445,1.790374e+06,2.959056e+06,7.804461,1.581186,117150.515595,9.565066e+05,1689.234043,422085.0,238182.0,102.742619,16159525.00,17.158333,3
2014-04-02,1459364.0,1.365117e+07,5.006861e+09,23527.0,0.168389,2.326614e+06,5.176962e+04,34.574898,3.835160,171229.636455,8.420618e+05,449.000000,137224.0,67292.0,13.421524,12596125.00,6.800000,3
2012-09-10,22766.0,4.199080e+05,2.694048e+06,3844.0,0.095205,9.834017e+04,2.115965e+01,2.497845,2.630430,301434.000000,2.335768e+07,224.213333,30504.0,33632.0,24.058630,9916800.00,16.550000,3

In [332]:
Random_Data.to_csv('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/RandomData.csv')

In [343]:
#Train_Data
Train_Data = pd.DataFrame()
Train_Data = Random_Data.iloc[0:2100, :]
Train_Data.to_csv('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/TrainData.csv')
Train_Data

,Bitcoin_my_wallet_num_users,Volume,Difficulty,wallet_num_transaction,Bitcoin_Avg_Block_Size,Miners_Revenue,Hash_Rate,Bitcoin_Cost_Transaction,Bitcoin_Cost_percentage_of_Transaction_Volume,Estimated_Transaction_Volume,Total_Output_Volume,num_transaction_per_Block,num_of_unique_addresses,num_of_transaction,Total_transaction_fees,Total_Bitcoins,Median_transaction_confirmation_time,Class
Date,,,,,,,,,,,,,,,,,,
2020-08-21,52845759.0,9.674630e+07,1.694780e+13,107827.0,1.344397,1.298833e+07,1.305844e+08,41.325023,0.856408,129046.707856,1.495714e+06,2027.722581,675988.0,314297.0,136.108508,18467206.25,11.725000,3
2012-07-06,11698.0,1.983366e+05,1.751455e+06,2008.0,0.068160,5.926606e+04,1.480110e+01,2.333769,5.300868,161200.000000,4.379832e+06,154.296774,23077.0,23916.0,16.384672,9399750.00,11.650000,3
2021-01-01,63530742.0,6.065241e+08,1.859959e+13,89018.0,1.352233,2.906805e+07,1.377640e+08,111.931054,0.669276,148420.304251,1.603396e+06,1732.080537,609741.0,258080.0,48.942701,18587787.50,10.816667,2
2017-02-11,11922903.0,1.076439e+07,4.221706e+11,71978.0,0.963661,1.792077e+06,2.917084e+06,7.074184,1.143913,162125.913611,1.418142e+06,1889.827338,474676.0,262686.0,117.080010,16157775.00,17.158333,2
2013-07-12,349434.0,3.785155e+06,2.616288e+07,7372.0,0.123121,3.647810e+05,1.963851e+02,9.048719,1.396064,285190.208023,8.812012e+05,239.000000,57072.0,40313.0,25.135946,11409975.00,8.583333,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-04-08,4168.0,2.743766e+05,1.626553e+06,107.0,0.017199,3.625440e+04,1.180504e+01,5.997419,2.919787,258683.000000,1.263160e+06,59.000000,10799.0,6045.0,3.833168,8742550.00,8.708333,3
2020-10-19,55115853.0,2.971624e+07,1.999734e+13,114911.0,1.275571,9.776921e+06,1.242591e+08,31.932566,0.602928,139860.200010,3.411625e+06,2431.432000,679146.0,303929.0,50.568632,18521668.75,20.425000,2
2017-03-28,12836242.0,9.014907e+06,4.757052e+11,81226.0,0.985684,2.192723e+06,3.665352e+06,7.714896,0.530614,409096.063969,2.332205e+06,1896.780645,553956.0,294001.0,233.221764,16242425.00,10.700000,3
2014-02-07,1212010.0,8.449900e+06,2.621404e+09,23173.0,0.186608,3.101609e+06,2.280438e+04,48.410448,2.694628,157383.641445,6.024400e+05,371.000000,131014.0,64069.0,12.343758,12365575.00,7.983333,2
2013-08-29,413824.0,1.673618e+06,6.575006e+07,10339.0,0.136291,6.105975e+05,6.340799e+02,10.056616,2.060973,235451.595215,7.272300e+05,293.000000,72629.0,60716.0,43.306453,11627225.00,5.933333,2

In [340]:
#Test_Data
Test_Data = pd.DataFrame()
Test_Data = Random_Data.iloc[2100:2530,:]
Test_Data.to_csv('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/TestData.csv')

In [342]:
#CV_Data
CV_Data = pd.DataFrame()
CV_Data = Random_Data.iloc[2530: , :]
CV_Data.to_csv('/Users/boxtim/Desktop/MFC Summer Project/Crypto MFC/CVData.csv')

In [ ]:
######### Finished